CREATE DATABASE DBDEPARTAMENTO;

USE DBDEPARTAMENTO;

CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT PRIMARY KEY auto_increment,
    NIVELACESSO CHAR(1) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR (11)  NOT NULL UNIQUE,
    RG VARCHAR (11) NOT NULL ,
    PIS VARCHAR(11) NOT NULL UNIQUE,
    GENERO CHAR(1),
    DATA_NASCI DATE NOT NULL,
    ESTADO_CIVIL VARCHAR(20),
    EMAIL VARCHAR(100) NOT NULL,
    ATIVO BOOL,
    DATA_ADMISSAO date
);

CREATE TABLE telefoneResidencial(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT,
	DDD char(2),
    NUMERO char(8),
    foreign key (IDFUNCIONARIO) REFERENCES funcionario(IDFUNCIONARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE telefoneCelular(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT,
	DDD char(2),
    NUMERO char(9),
    foreign key (IDFUNCIONARIO) REFERENCES funcionario(IDFUNCIONARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);		

CREATE TABLE ENDERECO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT,
    LOGRADOURO VARCHAR(100),
    CEP CHAR(8),
    BAIRRO VARCHAR(100),
    UF CHAR(2),
    COMPLEMENTO VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    NUMERO INT,
	foreign key (IDFUNCIONARIO) REFERENCES funcionario(IDFUNCIONARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
create TABLE ACESSO(
	IDACESSO INT primary KEY auto_increment NOT NULL,
    STATUSACESSO CHAR(1) NOT NULL,
    LOGIN VARCHAR(20) NOT NULL,
    SENHA VARCHAR(20) NOT NULL DEFAULT "123456",
    IDFUNCIONARIO INT NOT NULL,
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE CONTRATO(
		IDCONTRATO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        IDFUNCIONARIO INT NOT NULL,
        DATA_CONTRATO DATE NOT NULL,
        SALARIOBRUTO DECIMAL(5,2) NOT NULL,
        CARGO VARCHAR(20) NOT NULL,
        foreign key (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
		ON UPDATE CASCADE  
);

CREATE TABLE DEPARTAMENTO(
		IDDEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        IDGESTOR INT,
		DESCRICAO VARCHAR(100) NOT NULL,
        IDFUNCIONARIO INT NOT NULL,
        FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE FREQUENCIA(
	IDFREQUENCIA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	DATA_TRABALHADA DATE NOT NULL,
	PRESENTE BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE FREQUENCIAHORA(
	IDFREQUENCIAHORA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	IDFREQUENCIA INT NOT NULL,
	IDFUNCIONARIO INT NOT NULL,
	DATAHORA DATETIME,
	PRESENTE BOOLEAN NOT NULL DEFAULT TRUE,
	FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE FOLHA(
		IDFOLHA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        IDFUNCIONARIO INT NOT NULL,
        SALARIOLQIUIDO DECIMAL (5,2) NOT NULL,
        SALARIOBRUTO DECIMAL (5,2) NOT NULL,
        FGTS DECIMAL (5,2) NOT NULL,
        VT DECIMAL (5,2),
        CONVENIO DECIMAL(5,2) NOT NULL,
        IRRF DECIMAL (5,2) NOT NULL,
        INSS DECIMAL (5,2) NOT NULL,
        DESCFALTA DECIMAL(5,2),
        FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
);

CREATE TABLE DEMONSTRATIVO(
		IDDEMONSTRATIVO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        IDFREQUENCIA INT NOT NULL,
        IDFOLHA INT NOT NULL,
        IDFUNCIONARIO INT NOT NULL,
        SALARIOLQIUIDO DECIMAL (5,2) NOT NULL,
        SALARIOBRUTO DECIMAL (5,2) NOT NULL,
        DESCONTOS DECIMAL (5,2 ) NOT NULL,
        FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
        FOREIGN KEY (IDFREQUENCIA) REFERENCES FREQUENCIA(IDFREQUENCIA),
        FOREIGN KEY (IDFOLHA) REFERENCES FOLHA(IDFOLHA)
);
CREATE TABLE SALARIO(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT,
    SALARIO REAL,
    DATA_SALARIO DATE,
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE
    ON UPDATE CASCADE
);
SELECT * FROM ENDERECO where IDFUNCIONARIO = 11;
use dbdepartamento;
CREATE TABLE TESTE(ID INT PRIMARY KEY auto_increment, SALARIO REAL);
select * from telefoneresidencial;
DELETE FROM funcionario;
insert into teste values (default, 1000.10);
SELECT * FROM FUNCIONARIO;
UPDATE FUNCIONARIO
SET CPF = "12345678911"
WHERE IDFUNCIONARIO = 11